export const supportedLangList = {
  ABAP: "abap",
  Apex: "apex",
  "Azure CLI": "azcli",
  "Batch File": "bat",
  Bicep: "bicep",
  Cameligo: "cameligo",
  Clojure: "clojure",
  CoffeeScript: "coffeescript",
  C: "c",
  "C++": "cpp",
  "C#": "csharp",
  "Content Security Policy": "csp",
  CSS: "css",
  Cypher: "cypher",
  Dart: "dart",
  Dockerfile: "dockerfile",
  ECL: "ecl",
  Elixir: "elixir",
  Flow9: "flow9",
  "F#": "fsharp",
  Go: "go",
  GraphQL: "graphql",
  Handlebars: "handlebars",
  HCL: "hcl",
  HTML: "html",
  INI: "ini",
  Java: "java",
  JavaScript: "javascript",
  Julia: "julia",
  Kotlin: "kotlin",
  LESS: "less",
  Lexon: "lexon",
  Lua: "lua",
  M3: "m3",
  Markdown: "markdown",
  MDX: "mdx",
  MISP: "misp",
  MSDAX: "msdax",
  MySQL: "mysql",
  "Objective-C": "objective-c",
  Pascal: "pascal",
  Pascaligo: "pascaligo",
  Perl: "perl",
  Postiats: "postiats",
  "Power Query": "powerquery",
  PowerShell: "powershell",
  "Protocol Buffers": "proto",
  Python: "python",
  "Q#": "qsharp",
  R: "r",
  Razor: "razor",
  Redis: "redis",
  Redshift: "redshift",
  reStructuredText: "restructuredtext",
  Ruby: "ruby",
  Rust: "rust",
  SB: "sb",
  Scala: "scala",
  Scheme: "scheme",
  SCSS: "scss",
  Shell: "shell",
  Solidity: "sol",
  AES: "aes",
  SparkQL: "sparkql",
  SQL: "sql",
  ST: "st",
  Swift: "swift",
  SystemVerilog: "systemverilog",
  Verilog: "verilog",
  Tcl: "tcl",
  Twig: "twig",
  TypeScript: "typescript",
  VB: "vb",
  "WebGPU Shader Language": "wgsl",
  XML: "xml",
  YAML: "yaml",
  JSON: "json",
  PlainText: "plaintext",
};
